[[redirects]]
  from = "/jikan/*"
  to = "https://api.jikan.moe/v4/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/consumet/*"
  to = "https://c.delusionz.xyz/:splat"
  status = 200
  force = true
