[[redirects]]
  from = "/jikan/*"
  to = "https://api.jikan.moe/v4/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/consumet/*"
  to = "https://consumet-api.vercel.app/:splat"
  status = 200
  force = true
