[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "encrypted-media=*, autoplay=*, picture-in-picture=*, web-share=*"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/malsync/*"
  to = "https://api.malsync.moe/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/jikan/*"
  to = "https://api.jikan.moe/v4/:splat"
  status = 200
  force = true
